version: "2"
services:
  app:
    image: hms-app:dev
    ports:
      - "9000:8000"
    environment:
      DB_HOST: host.docker.internal
    volumes:
      - .:/usr/src/app
  web: 
    image: hms-web:dev
    ports:
      - "3001:3000"
    volumes:
      - .:/user/src/app
  